# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Koober' do
  # Comment the next line if you don't want to use dynamic frameworks

  use_frameworks!
  # Pods for Koober

    pod 'PromiseKit', '6.8.4'
    pod 'RxSwift', '4.5.0'
    pod 'RxCocoa', '4.5.0'
    pod 'Kingfisher', '5.3.1'

end

target 'Koober_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks

  use_frameworks!
  # Pods for Koober_iOS

    pod 'PromiseKit', '6.8.4'
    pod 'RxSwift', '4.5.0'
    pod 'RxCocoa', '4.5.0'
    pod 'Kingfisher', '5.3.1'
end

target 'KooberKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KooberKit

    pod 'PromiseKit', '6.8.4'
    pod 'RxSwift', '4.5.0'
    pod 'RxCocoa', '4.5.0'
    pod 'Kingfisher', '5.3.1'

end

target 'KooberUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks

  use_frameworks!
  # Pods for KooberUIKit

    pod 'PromiseKit', '6.8.4'
    pod 'RxSwift', '4.5.0'
    pod 'RxCocoa', '4.5.0'
    pod 'Kingfisher', '5.3.1'

end
